# Quantitative Momentum Strategy Adapted From CodeAcademy (Nick McCullum)

"'Momentum investing' means investing in the stocks that have increased in price the most.

For this project, I am going to build an investing strategy that selects the 50 stocks with the highest price momentum. From there, I will calculate recommended trades for an equal-weight portfolio of these 50 stocks." - Nick McCullum

In Nick McCullum's data, there should be a WLTW stock. However, I deleted it cause there was no data stored about it. As a result, there would be a KeyError whenever I ran it. 

## Library Imports

In [16]:
import numpy as np
import pandas as pd
import requests
import math
from scipy import stats
import xlsxwriter

## Importing Our List of Stocks

In [2]:
stocks = pd.read_csv('sp_500_stocks.csv')
from apitoken import IEX_CLOUD_API_TOKEN

## Making Our First API Call

In [3]:
symbol = 'GOOGL'
api_url = f'https://sandbox.iexapis.com/stable/stock/{symbol}/stats?token={IEX_CLOUD_API_TOKEN}'
data = requests.get(api_url).json()
data

{'companyName': 'Alphabet Inc',
 'marketcap': 1768277647341,
 'week52high': 3112.04,
 'week52low': 1817.84,
 'week52highSplitAdjustOnly': 3091.46,
 'week52lowSplitAdjustOnly': 1811.58,
 'week52change': 0.3826471272758606,
 'sharesOutstanding': 312078469,
 'float': 0,
 'avg10Volume': 1774542,
 'avg30Volume': 1531488,
 'day200MovingAvg': 2887,
 'day50MovingAvg': 2961.09,
 'employees': 141738,
 'ttmEPS': 105.8,
 'ttmDividendRate': 0,
 'dividendYield': 0,
 'nextDividendDate': '',
 'exDividendDate': '',
 'nextEarningsDate': '2022-02-01',
 'peRatio': 24.97506069813454,
 'beta': 1.280301013405554,
 'maxChangePercent': 10.393607133457712,
 'year5ChangePercent': 2.211701580625539,
 'year2ChangePercent': 0.7823767975556483,
 'year1ChangePercent': 0.3909398243706584,
 'ytdChangePercent': -0.10192604340086918,
 'month6ChangePercent': 0.02275252421886682,
 'month3ChangePercent': -0.08484151384761131,
 'month1ChangePercent': -0.09299677196365322,
 'day30ChangePercent': -0.11277558240878538,
 'day5ChangePercent': -0.06863238040668349}

## Parsing Our API Call

In [4]:
data['year2ChangePercent']

0.7823767975556483

## Executing A Batch API Call & Building Our DataFrame

In [5]:
my_columns = ['Ticker','Stock Price','Year 2 Change Percent', 'Number of Shares to Buy']

dataFrame = pd.DataFrame(columns = my_columns) # two dimensional 
dataFrame

# will yield n number of chunks that forms a list
def chunks(lst, n):
    for i in range(0,len(lst),n):
        yield lst[i:i + n]
    
symbol_groups = list(chunks(stocks['Ticker'], 100))
symbol_strings = []

for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))
dataFrame = pd.DataFrame(columns = my_columns)


for symbol_string in symbol_strings:
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch?symbols={symbol_string}&types=price,stats&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
    # print(symbol_string.split(','))
    # print(data)
    for symbol in symbol_string.split(','):
        dataFrame = dataFrame.append(
            pd.Series(
                [
                    symbol, 
                    data[symbol]['price'],
                    data[symbol]['stats']['year2ChangePercent'],
                    'N/A'
                ],
                index = dataFrame.columns
            ),
            ignore_index = True
        )

dataFrame

    Ticker  Stock Price Year 2 Change Percent Number of Shares to Buy
0        A       144.18              0.563325                     N/A
1      AAL        17.00             -0.405117                     N/A
2      AAP       226.64              0.553793                     N/A
3     AAPL       164.45              1.104278                     N/A
4     ABBV       132.01              0.681795                     N/A
..     ...          ...                   ...                     ...
499    YUM       126.47              0.226024                     N/A
500    ZBH       125.43             -0.172381                     N/A
501   ZBRA       509.26              0.959606                     N/A
502   ZION        62.39              0.325436                     N/A
503    ZTS       201.71               0.43708                     N/A

[504 rows x 4 columns]

## Removing Low-Momentum Stocks

In [6]:
dataFrame.sort_values('Year 2 Change Percent', ascending = False, inplace = True) # inplace modifies the orginal pands dataframe
dataFrame = dataFrame[:50]
dataFrame.reset_index(inplace = True)
dataFrame

    index Ticker  Stock Price Year 2 Change Percent Number of Shares to Buy
0      78   CARR        47.90              2.993944                     N/A
1     345   NVDA       242.41              2.834196                     N/A
2     275     LB        83.80              2.491805                     N/A
3     179    FCX        41.85              2.424395                     N/A
4     299   MCHP        74.13              1.817976                     N/A
5      23    ALB       222.34              1.720341                     N/A
6     195   FTNT       297.50              1.520603                     N/A
7     385    PWR       102.85              1.412712                     N/A
8     489    WST       381.90              1.400726                     N/A
9      31    AMD       118.84              1.378439                     N/A
10    410   SIVB       585.76              1.334529                     N/A
11    444   TSCO       218.54              1.333994                     N/A
12    174      F        21.34              1.299588                     N/A
13    351   ODFL       299.93              1.187386                     N/A
14     29   AMAT       136.18              1.184841                     N/A
15    128     DE       371.08              1.171732                     N/A
16    266   KLAC       391.16              1.171244                     N/A
17     37   ANET       119.16              1.160471                     N/A
18      3   AAPL       164.45              1.104278                     N/A
19    148    DVN        46.17              1.102793                     N/A
20    288   LRCX       630.91              1.017603                     N/A
21     85   CDNS       154.80              1.016085                     N/A
22    415   SNPS       318.19              1.004176                     N/A
23    273    KSU       308.21              0.987943                     N/A
24    501   ZBRA       509.26              0.959606                     N/A
25    462    URI       309.35              0.957702                     N/A
26    436    TGT       220.50              0.957518                     N/A
27    287    LOW       233.54              0.931479                     N/A
28    344    NUE        95.96              0.920526                     N/A
29    314    MOS        40.47              0.917379                     N/A
30    494   XLNX       188.62              0.915313                     N/A
31    243   INTU       547.80              0.913795                     N/A
32    407   SCHW        91.70              0.909506                     N/A
33    318     MS       101.06              0.895654                     N/A
34     50   AVGO       554.78              0.865305                     N/A
35    173    EXR       199.01              0.860986                     N/A
36    388   QCOM       164.97              0.859865                     N/A
37    256    JCI        74.47              0.856826                     N/A
38    356   OTIS        84.95              0.844794                     N/A
39    461    UPS       208.99              0.841508                     N/A
40     34    AMP       309.20              0.837573                     N/A
41    150   DXCM       425.40              0.837474                     N/A
42    320   MSFT       300.71               0.83221                     N/A
43    319   MSCI       516.51              0.829476                     N/A
44    395    RHI       110.00              0.826913                     N/A
45    166    ETN       168.29              0.807425                     N/A
46    408    SEE        69.28               0.79883                     N/A
47    283    LLY       245.99              0.789781                     N/A
48    205  GOOGL      2632.50              0.788199                     N/A
49    236   IDXX       503.85              0.784569                     N/A

## Calculating the Number of Shares to Buy

In [8]:
def portfolio():
    global portfolio_size
    portfolio_size = input("Enter the size of your portfolio ")
    
    try:
        float(portfolio_size)
    except ValueError:
        print('That is not a number! \nPlease try again ')
        portfolio_size = input("Enter the size of your portfolio ")
        
portfolio()
print(portfolio_size)

Enter the size of your portfolio 1000000000
1000000000

In [9]:
position_size = float(portfolio_size) / len(dataFrame.index)
# print(position_size)
for i in range(0, len(dataFrame)):
    dataFrame.loc[i, 'Number of Shares to Buy'] = math.floor(position_size / dataFrame.loc[i, 'Stock Price'])
    
dataFrame

/Users/jiyoonsung/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

    index Ticker  Stock Price Year 2 Change Percent Number of Shares to Buy
0      78   CARR        47.90              2.993944                  417536
1     345   NVDA       242.41              2.834196                   82504
2     275     LB        83.80              2.491805                  238663
3     179    FCX        41.85              2.424395                  477897
4     299   MCHP        74.13              1.817976                  269796
5      23    ALB       222.34              1.720341                   89952
6     195   FTNT       297.50              1.520603                   67226
7     385    PWR       102.85              1.412712                  194457
8     489    WST       381.90              1.400726                   52369
9      31    AMD       118.84              1.378439                  168293
10    410   SIVB       585.76              1.334529                   34143
11    444   TSCO       218.54              1.333994                   91516
12    174      F        21.34              1.299588                  937207
13    351   ODFL       299.93              1.187386                   66682
14     29   AMAT       136.18              1.184841                  146864
15    128     DE       371.08              1.171732                   53896
16    266   KLAC       391.16              1.171244                   51129
17     37   ANET       119.16              1.160471                  167841
18      3   AAPL       164.45              1.104278                  121617
19    148    DVN        46.17              1.102793                  433181
20    288   LRCX       630.91              1.017603                   31700
21     85   CDNS       154.80              1.016085                  129198
22    415   SNPS       318.19              1.004176                   62855
23    273    KSU       308.21              0.987943                   64890
24    501   ZBRA       509.26              0.959606                   39272
25    462    URI       309.35              0.957702                   64651
26    436    TGT       220.50              0.957518                   90702
27    287    LOW       233.54              0.931479                   85638
28    344    NUE        95.96              0.920526                  208420
29    314    MOS        40.47              0.917379                  494193
30    494   XLNX       188.62              0.915313                  106033
31    243   INTU       547.80              0.913795                   36509
32    407   SCHW        91.70              0.909506                  218102
33    318     MS       101.06              0.895654                  197902
34     50   AVGO       554.78              0.865305                   36050
35    173    EXR       199.01              0.860986                  100497
36    388   QCOM       164.97              0.859865                  121234
37    256    JCI        74.47              0.856826                  268564
38    356   OTIS        84.95              0.844794                  235432
39    461    UPS       208.99              0.841508                   95698
40     34    AMP       309.20              0.837573                   64683
41    150   DXCM       425.40              0.837474                   47014
42    320   MSFT       300.71               0.83221                   66509
43    319   MSCI       516.51              0.829476                   38721
44    395    RHI       110.00              0.826913                  181818
45    166    ETN       168.29              0.807425                  118842
46    408    SEE        69.28               0.79883                  288683
47    283    LLY       245.99              0.789781                   81304
48    205  GOOGL      2632.50              0.788199                    7597
49    236   IDXX       503.85              0.784569                   39694

## Building a Better (and More Realistic) Momentum Strategy

In [12]:
hqm_col = [
    'Ticker',
    'Price',
    'Number of Shares to Buy',
    'Two-Years Price Return',
    'Two-Years Return Percentile',
    'Six-Months Price Return',
    'Six-Months Return Percentile',
    'Three-Months Price Return',
    'Three-Months Return Percentile',
    'One-Months Price Return',
    'One-Months Return Percentile'
]

hqm_dataFrame = pd.DataFrame(columns = hqm_col)
# hqm_dataFrame

for symbol_string in symbol_strings:
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch?symbols={symbol_string}&types=price,stats&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(','):
        hqm_dataFrame = hqm_dataFrame.append(
            pd.Series(
                [symbol, data[symbol]['price'], 'N/A', data[symbol]['stats']['year2ChangePercent'], 'N/A', data[symbol]['stats']['month6ChangePercent'], 'N/A', data[symbol]['stats']['month3ChangePercent'], 'N/A', data[symbol]['stats']['month1ChangePercent'], 'N/A'],
                index = hqm_col
            ),
            ignore_index = True
        )
        
hqm_dataFrame

,Ticker,Price,Number of Shares to Buy,Two-Years Price Return,Two-Years Return Percentile,Six-Months Price Return,Six-Months Return Percentile,Three-Months Price Return,Three-Months Return Percentile,One-Months Price Return,One-Months Return Percentile
0,A,143.67,N/A,0.562482,N/A,-0.075785,N/A,-0.123996,N/A,-0.106338,N/A
1,AAL,16.40,N/A,-0.412479,N/A,-0.238607,N/A,-0.184494,N/A,-0.100758,N/A
2,AAP,231.63,N/A,0.572333,N/A,0.092498,N/A,-0.028632,N/A,-0.015283,N/A
3,AAPL,164.53,N/A,1.128341,N/A,0.124464,N/A,0.090209,N/A,-0.061725,N/A
4,ABBV,135.90,N/A,0.66627,N/A,0.154853,N/A,0.235135,N/A,0.02708,N/A
...,...,...,...,...,...,...,...,...,...,...,...
499,YUM,124.35,N/A,0.229139,N/A,0.073941,N/A,-0.016515,N/A,-0.071545,N/A
500,ZBH,126.82,N/A,-0.171995,N/A,-0.235772,N/A,-0.195796,N/A,0.000674,N/A
501,ZBRA,516.71,N/A,0.993516,N/A,-0.075526,N/A,-0.075564,N/A,-0.153953,N/A
502,ZION,63.66,N/A,0.328409,N/A,0.213167,N/A,-0.038617,N/A,0.001694,N/A
503,ZTS,203.01,N/A,0.432986,N/A,0.014644,N/A,-0.038108,N/A,-0.161769,N/A

## Calculating Momentum Percentiles

We now need to calculate momentum percentile scores for every stock in the universe. More specifically, we need to calculate percentile scores for the following metrics for every stock:

* `One-Year Price Return`
* `Six-Month Price Return`
* `Three-Month Price Return`
* `One-Month Price Return`

Here's how we'll do this:

In [17]:
time_periods = ['Two-Years', 'Six-Months', 'Three-Months', 'One-Month']

for row in hqm_dataFrame.index:
    for time_period in time_periods:
        hqm_dataFrame.loc[row, f'{time_period} Return Percentile'] = stats.percentileofscore(hqm_dataFrame[f'{time_period} Price Return'], hqm_dataFrame.loc[row, f'{time_period} Price Return'])
        
hqm_dataFrame

TypeError: '<' not supported between instances of 'NoneType' and 'float'

## Calculating the HQM Score

We'll now calculate our `HQM Score`, which is the high-quality momentum score that we'll use to filter for stocks in this investing strategy.

The `HQM Score` will be the arithmetic mean of the 4 momentum percentile scores that we calculated in the last section.

To calculate arithmetic mean, we will use the `mean` function from Python's built-in `statistics` module.

## Selecting the 50 Best Momentum Stocks

As before, we can identify the 50 best momentum stocks in our universe by sorting the DataFrame on the `HQM Score` column and dropping all but the top 50 entries.

## Calculating the Number of Shares to Buy

We'll use the `portfolio_input` function that we created earlier to accept our portfolio size. Then we will use similar logic in a `for` loop to calculate the number of shares to buy for each stock in our investment universe.

## Formatting Our Excel Output

We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization. However, the tradeoff for this is that the library can seem very complicated to new users. Accordingly, this section will be fairly long because I want to do a good job of explaining how XlsxWriter works.

## Creating the Formats We'll Need For Our .xlsx File

You'll recall from our first project that formats include colors, fonts, and also symbols like % and $. We'll need four main formats for our Excel document:

* String format for tickers
* \$XX.XX format for stock prices
* \$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase

Since we already built our formats in the last section of this course, I've included them below for you. Run this code cell before proceeding.

In [ ]:
background_color = '#0a0a23'
font_color = '#ffffff'

string_template = writer.book.add_format(
        {
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

dollar_template = writer.book.add_format(
        {
            'num_format':'$0.00',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

integer_template = writer.book.add_format(
        {
            'num_format':'0',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

percent_template = writer.book.add_format(
        {
            'num_format':'0.0%',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

## Saving Our Excel Output

As before, saving our Excel output is very easy: